### ISSUE TITLE
toString() not working?

### ISSUE THREAD

**Issue by HFolkertH** [cincheo/dlite#10]
Hello

I have a text-field with default value '0". Next I have a button that should add 1 to the current value and show it again.

I tried parseInt, toString(), sting(), toFixed()   but I can not get that button to display the incremented value.
Whats the Action to achieve this?

Just a silly test:
![image](https://user-images.githubusercontent.com/22573455/168812654-aabad8cd-0cbc-4237-86b7-f001bb967f3f.png)

**Comment by renaudpawlak** [comment]
Your arguments should be a comma-separated list of valid JavaScript expressions (one for each argument). 

To increment the value of your text field, it should be something like : 

```javascript
(Number.parseFloat($d(target)) + 1).toFixed(2)
```

Note that ``$d(target)`` is a useful shortcut to access the data model of a component. It is the same as ``target.dataModel``. 

Now, if you define your input type as a number (instead of a text field), the dataModel value will be a number... So you don't need to parse it.  Something like : 

```javascript
$d(target) + 1)
```

...should work perfectly :)

It you don't manage to make it work from there, I will send you a DLite project that does the job.

**Comment by HFolkertH** [comment]
Thanx. Works like a charm now.

By the way:  I am trying to build the 7Gui tasks of Eugene Kiss (https://7guis.github.io/7guis/ ) in dlite. 
Could be a nice example project sometime.

**Comment by renaudpawlak** [comment]
Excellent. I did not know about this benchmark. Nice initiative. I am curious to see the outcome and I'll try to take a peek at it when I'll have some time.

**Comment by renaudpawlak** [comment]
FYI, DLite now supports copy/paste from system clipboard. You can copy paste an increment/decrement counter example directly in your project ;) See #12. It will make it extremely easy to share components in the future.

**Comment by hasen666** [comment]
> Thanx. Works like a charm now.
> 
> By the way: I am trying to build the 7Gui tasks of Eugene Kiss (https://7guis.github.io/7guis/ ) in dlite. Could be a nice example project sometime.

interesting ! let me know your achievement on this and thank for your participation here.

**Comment by renaudpawlak** [comment]
>> interesting ! let me know your achievement on this and thank for your participation here.

Agreed! Please let me know too how it goes and I would be glad to help if you encounter any blocking situation :)
